name: payu
channels:
  - accessnri
  - conda-forge
dependencies:
  - python==3.10
  - accessnri::payu==1.3.0
  - f90nml
  - nco
  - pytest
  - xarray
  - mule
  - um2nc
  - accessnri::yamanifest
  - netcdf4=*=nompi_*
  - experiment-generator
  - experiment-runner
  - mnctools
  - addmeta
